name:  Test AWS Secrets

on: [workflow_dispatch]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show Environment Variables (for debug)
        run: |
          echo "AWS_ACCESS_KEY_ID is set: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS_SECRET_ACCESS_KEY is set: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
          echo "AWS_REGION is: ${{ secrets.AWS_REGION }}"

